---
title: Games and Matchups
---
erDiagram
    DIM_MATCHUPS ||--|{ DIM_GAMES : describe 
     
    DIM_GAMES {
        id bigint PK "NN"
        matchup_id bigint FK 
        start_time timestamp "NN"
        end_time timestamp "NN"
    }

    DIM_MATCHUPS {
        id bigint PK "NN"
        home_team_id bigint FK "NN" 
        away_team_id bigint FK "NN"
        arena_id bigint FK 
    }