---
title: Players and Teams 
---

erDiagram
    dim_teams ||--|{ dim_rosters : are-comprised-of
    dim_seasons ||--|{ dim_rosters : are-comprised-of
    dim_rosters }|--|{ dim_players : are-comprised-of
    dim_rosters }|--|{ dim_players_rosters_bios : are-comprised-of

    dim_teams {
        id bigint PK "NN"
        location varchar(20) "NN"
        mascot varchar(20) "NN" 
    }

    dim_seasons {
        id bigint PK "NN" 
        start_year year "NN" 
        end_year year "NN"
    }

    dim_rosters {
        id bigint PK "NN"
        team_id bigint FK "NN" 
        player_id bigint FK "NN"
        season_id bigint FK "NN"
        bio_id bigint FK "NN"
    }

    dim_players_rosters_bios {
        id bigint PK "NN"
        number int "NN"
        height_meters float "NN" 
        weight_grams float "NN"
        positions_ids array<bigint> FK "NN"
    }