classDiagram

    class GameStatsProvider {
        -PlayerRepository player_repo
        -CountingStatsRepository count_stat_repo 
        -AggregateStatsRepository agg_stat_repo
        -AdvancedStatsRepository adv_stat_repo
        
        #list_counting_stats_by_date(Date start_date, Date end_date) : CountingStatsResponse
        #list_aggregate_stats_by_date(Date start_date, Date end_date) : AggregateStatsResponse
        #list_advanced_stats_by_date(Date start_date, Date end_date) : AdvancedStatsResponse
    }

    GameStatsProvider : +list_stats(
        StatsSearchOptions search_options,
        StatsDisplayOptions display_options,
        List<StatType> stat_types
    ) : StatsResponse