classDiagram
    class SeasonStatsProvider {
        -GameStatsProvider statProvider 
        -SeasonService seasonService

        +list_stats(StatSearchOptions search_options) : SeasonStatsResponse
    }
