classDiagram
    class Player {
        -int id
        -string first_name
        -string last_name
        -float height_meters
        -float weight_grams
        -date birth_date

        +get_display_name() : string 
        +get_age() : int
        +get_height(metric metric_type) : float 
        +get_weight(metric metric_type) : float
    }

    class PlayerRepository {
        -PlayerModel playerModel
        -TeamModel teamModel

        +get_by_id(int id) : Player | None 
        +find_by_team(int team_id, int season_id) : List<Player>
        +find_by_team(int team_id, date start_date, date end_date) : List<Player>
        
        +create(Player player) : Player 
        +update(Player player) : Player
        +upsert(Player player) : Player
    }