---
title: Players Stats
---

erDiagram
    dim_players ||--|{ fact_flat_counting_stats : accrue
    dim_games ||--|{ fact_flat_counting_stats : represent
    dim_stat_offense ||--|{ fact_flat_counting_stats : represents
    dim_stat_offense_non_scoring ||--|{ fact_flat_counting_stats : represents
    dim_stat_defense ||--|{ fact_flat_counting_stats : represents
    dim_stat_attributes ||--|| dim_stat_offense : describe 
    dim_stat_attributes ||--|| dim_stat_offense_non_scoring : describe 
    dim_stat_attributes ||--|| dim_stat_defense : describe 

    fact_flat_counting_stats {
        game_id bigint FK "NN"
        player_id bigint FK "NN" 
        starting boolean "NN"
        mp float "NN" 
        stat_offense_scoring_id int FK "NN"
        stat_offense_non_scoring int FK "NN"
        stat_defense_id int FK "NN"
    }

    dim_stat_offense_scoring {
        id int "NN"
        fgm_2p int "NN"
        fga_2p int "NN"
        fgm_3p int "NN"
        fga_3p int "NN"
        ftm int "NN"
        fta int "NN"
    }

    dim_stat_offense_non_scoring {
        id int "NN"
        orb int "NN" 
        ast int "NN"
        tov int "NN"
    }

    dim_stat_defense {
        id int "NN"
        stl int "NN"
        blk int "NN"
        drb int "NN"
    }

    dim_stat_attributes {
        id bigint PK "NN" 
        display_name varchar(35) "NN" 
        description varchar(140) "NN"
        field_identifier varchar(10) "NN"
        type stat_type "NN"
    }