---
title: Player-Descriptors
---

erDiagram
    dim_players }|--|{ dim_players_positions : play
    dim_players }|--|{ dim_players_nationalities : have

    dim_players {
        id bigint PK "NN"
        first_name varchar(20) "NN"
        last_name varchar(20) "NN" 
        birth_date timestamp "NN"
    }
    
    dim_players_nationalities {
        id bigint PK "NN" 
        player_id bigint FK "NN" 
        country country "NN"
        created_at timestamp "NN"
        updated_at timestamp "NN"
    }

    %% TODO: MOVE THIS TO ROSTER 
    %% dim_players_positions {
    %%     player_id bigint PK, FK "NN" 
    %%     position_id bigint PK, FK "NN"
    %%     season_id bigint PK, FK "NN"
    %% }