---
config:
  theme: redux-dark
title: Basic ETL Flow
---
flowchart LR
    subgraph s0["Event Scheduler"]
        get_events["Get Scheduled Events from DB"] --> for_each_event["For Each Event"]
        for_each_event --> event_compl["Event Completed Success?"]
        event_compl --"Yes"--> skip_event["Skip Event"]
        event_compl --"No"--> event_in_progress["Event In Progress?"]
        event_in_progress --"Yes"--> skip_event_0["Skip Event"]
        event_in_progress --> event_scheduled["Event Scheduled?"]
        event_scheduled --"Yes"--> cool_off_period_passed["Cool Off Period Passed?"]
        cool_off_period_passed --"No"--> skip_event_1["Skip Event"]
        cool_off_period_passed --"Yes"--> event_errored["Event Errored?"]
        event_scheduled --"No"-->event_errored
        event_errored --"Yes"--> event_errored_x_times["Num Retries >= Allowed Retries?"]
        event_errored_x_times --"Yes"--> skip_event_2["Skip Event"]
        event_errored_x_times --"No"--> write_event_triggered["Write Event Triggered to DB"]
    end 
    s0--"Job Triggered"-->s1
    subgraph s1["Job Running"]
        f_dp["ServiceProvider.find"] --> sp_dne["Service Doesn't Exist"]
        sp_dne --"No"--> service_does_not_exist_error["Service Does Not Exist Error"]
        sp_dne --"Yes"--> provider_invoke["Service->invoke"]
        provider_invoke --> provider_invoke_errored["Service->invoke Errored?"]
        provider_invoke_errored --"Yes"--> write_event_errored["Write Event Errored to DB"]
        provider_invoke_errored --"No"--> write_event_completed_success["Write Event Completed Success to DB"]
        write_event_completed_success --> exit["Exit"]
    end
    provider_invoke --> s2
    subgraph s2["Extract Job (Service: DataOrchestrator<T, J>)"]
        dp_extract["DataProvider.extract_raw_data"] --> fp_write["FileProcessor.write"]
        fp_write --> sp_upload_file("StorageProvider.upload_file")
        fp_write --> dp_transform["DataProvider.process_raw_data"]
        dp_transform --> fp_write_tfd["FileProcessor.write"]
        fp_write_tfd --> sp_upload_file_d["StorageProvider.upload_file"]
        sp_upload_file_d --> dw_write["Insert Processed Data to DB"]
        dw_write --> dw_validate_write["Validate Inserts"]
        dw_validate_write --> inserts_failed["Inserts Failed?"]
        inserts_failed --"Yes"--> log_inserts_failed["Log Inserts Failed"]
        inserts_failed --"No"--> exit_1["Exit"]
    end
