classDiagram
    class Team {
        -int id
        -string location 
        -string mascot

        +get_display_name()
    }

    class TeamRepository {
        -TeamModel model 

        +get_by_id(int team_id) : Team | None 
    }

    class Roster {
        -int id 
        -Team team 
        -Season season 
        -List<Player> players 

        +get_display_name()
        +get_players_display()
    }

    class RosterRepository {
        -RosterModel model 

        +get_by_id(int roster_id) : Roster | None 
    }