classDiagram
    class CountingStatsResponse {
        -int fgm_2p 
        -int fga_2p
        -int fgm_3p  
        -int fga_3p  
        -int ftm  
        -int fta  
        -int orb   
        -int ast  
        -int tov  
        -int of  
        -int df  
        -int stl  
        -int blk  
        -int drb  
    }